# === SERVER ===
server.port=${PORT:8080}
spring.application.name=hamburgueria-api

# === DATASOURCE - Render injeta DATABASE_URL automaticamente ===
# Local: H2 | Prod: PostgreSQL (Render)
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:hamburgueria}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# === SQL INIT - PARA O SEED 110% ===
spring.sql.init.mode=always

# === JWT ===
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# === H2 Console (só local) ===
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === Swagger ===
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# === Actuator 110% ===
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always